services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=boards'
      - 'POSTGRES_PASSWORD=secretpass'
      - 'POSTGRES_USER=drew'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secretpass'
      - 'RABBITMQ_DEFAULT_USER=drew'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'